name: analyses

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ github.sha }}

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Cached node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Eslint
        run: pnpm run lint:check

  prettier:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Cached node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Prettier
        run: pnpm run prettier:check

  typescript:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Cached node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Typescript
        run: pnpm run ts:check

  unit_tests:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Cached node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Unit tests
        run: pnpm run test:unit
